[package]
name = "usb-gadget"
description = "Expose standard or fully custom USB peripherals (gadgets) through a USB device controller (UDC) on Linux."
categories = ["hardware-support", "os::linux-apis"]
keywords = ["usb", "gadget", "peripheral", "configfs", "functionfs"]
license = "Apache-2.0"
repository = "https://github.com/surban/usb-gadget"
authors = ["Sebastian Urban <surban@surban.net>"]
rust-version = "1.73"
version = "0.3.0"
edition = "2021"

[features]
default = []

[dependencies]
tokio = { version = "1.32", features = ["net", "rt", "sync"], optional = true }
proc-mounts = "0.3"
strum = { version = "0.25", features = ["derive"] }
macaddr = "1.0"
nix = { version = "0.27", features = ["mount", "event", "ioctl", "poll", "fs"] }
bitflags = "2.4"
byteorder = "1"
log = "0.4"
libc = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "time"] }
tempfile = "3"
rusb = "0.9"
env_logger = "0.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
