[package]
name = "usb-gadget"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
tokio = { version = "1.32", features = ["net", "fs", "sync", "rt"] }
proc-mounts = "0.3"
strum = { version = "0.25", features = ["derive"] }
async-trait = "0.1"
